version: "3.5"

services:
  sonarqube:
    build:
      context: docker/sonarqube
    hostname: sonarqube
    container_name: cont-sonarqube
    environment:
      TZ: ${TIME_ZONE}

    volumes:
      - ./docker/sonarqube/bash:/root/bash

    ports:
      - ${SONAR_HTTP_PORT}:3030

    networks:
      - sonarqube-net
      - mariadb-univ_net

networks:
  sonarqube-net:
  mariadb-univ_net:
    external: true
