version: "3.5"

services:
  sonarqube:
    build:
      context: docker
    hostname: sonarqube
    container_name: cont-sonarqube
    environment:
      TZ: ${TIME_ZONE}
      SONARQUBE_JDBC_USERNAME: ${DB_USER}
      SONARQUBE_JDBC_PASSWORD: ${DB_PASSWORD}
      SONARQUBE_JDBC_URL: "jdbc:mysql://mysql:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true"

    volumes:
      - ./app:/app

    ports:
      # localhost:3500
      - ${HOST_PORT}:9000

    networks:
      - sonarqube-net
      - mariadb-univ_net

networks:
  sonarqube-net:
  mariadb-univ_net:
    external: true
