version: "3.5"

services:
  sonarqube:
    build:
      context: docker
    hostname: sonarqube
    container_name: cont-sonarqube
    environment:
      TZ: ${TIME_ZONE}

    volumes:
      - ./app:/app

    ports:
      # localhost:3500
      - ${HOST_PORT}:9000

    networks:
      - sonarqube-net
      - mariadb-univ_net

networks:
  sonarqube-net:
  mariadb-univ_net:
    external: true
