# symf03
# docker-compose up --build 
version: "3.3"

services:
  dbmaria:
    build: ./mariadb/
    container_name: cmari03
    hostname: hmari03

    environment:
      MYSQL_ROOT_PASSWORD: 1234

    volumes:
      - ${FOLDER_DB}/initdb:/docker-entrypoint-initdb.d/
      - ${FOLDER_DB}/mysql:/var/lib/mysql
    
    ports:
      - "3306:3306"
    networks:
      net:
        ipv4_address:
          172.19.0.2

    command:
      'mysqld --innodb-flush-method=fsync'

  php:
    build: ./php7_fpm/
    container_name: cphp03
    hostname: hphp03
    volumes:
      - ${FOLDER_WWW}:/var/www/html
    networks:
      net:
        ipv4_address:
          172.19.0.3
    entrypoint: 
      - /home/user/bash_scripts/entrypoint.sh
    
  nginx:
    build: ./nginx/
    container_name: cngx03
    hostname: hngx03
    ports:
      - "3000:80"
    volumes:
      - ${FOLDER_WWW}:/var/www/html
      - ./nginx/symfony.conf:/etc/nginx/conf.d/default.conf
    networks:
      net:
        ipv4_address:
          172.19.0.4

networks:
    net:
      ipam:
        config:
          - subnet: 172.19.0.0/24
