version: "3.9"

services:
  ubuntu1804:
    container_name: cont-ubuntu1804
    hostname: ubuntu1804
    
    build:
      context: .
      dockerfile: ./Dockerfile
    
    volumes:
      - ./data:/app/data
      - ./bash:/app/bash

    entrypoint: /app/bash/entrypoint.sh