version: "3.9"

services:
  python38:
    container_name: cont-ubuntu1804
    hostname: ubuntu1804
    
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    
    volumes:
      - ./data:/app/data

    entrypoint: ./app/entrypoint.sh