version: '3'

services:
  web:
    # image: nginx:latest
    build: ./nginx/
    container_name: cngx
    hostname: hngx
    ports:
      - "5000:80"
    volumes:
      - ./app:/code
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - netngx

  php:
    # image: php:7-fpm
    build: ./php7_fpm/
    container_name: cfpm
    hostname: hfpm
    volumes:
      - ./app:/code
    networks:
      - netngx      

networks:
  netngx:
    driver: bridge