version: '3'

services:
  db:
    # dockerfile
    build: ./mariadb/

  web:
    build: ./nginx/
    container_name: cngx
    ports:
      - "3000:80"
    volumes:
      - ./app:/code
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - netxnmp

  php:
    build: ./php7_fpm/
    container_name: cfpm
    volumes:
      - ./app:/code
    networks:
      - netxnmp      

networks:
  netxnmp:
    driver: bridge