version: "3"

services:
  web:
    # image: nginx:latest
    build: ./nginx/
    container_name: cont-web1
    hostname: hostweb
    ports:
      - "3000:80"
    volumes:
      - ./app:/code
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - netphpxdebug

  php:
    # image: php:7-fpm
    build: ./php/
    container_name: cont-php1
    hostname: hostphp
    volumes:
      - ./app:/code
    networks:
      - netphpxdebug      

networks:
  netphpxdebug:
    driver: bridge