version: "3"

services:
  web:
    # image: nginx:latest
    build: ./nginx/
    container_name: cont-web1
    hostname: hostweb
    ports:
      - "3000:80"
    volumes:
      - ./app:/code
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - netphpxdebug

  php:
    # image: php:7-fpm
    build: ./php/
    container_name: cont-php1
    hostname: hostphp
    environment:
      PHP_IDE_CONFIG: serverName=ServXdebug
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9005
    volumes:
      - ./app:/code
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - netphpxdebug      

networks:
  netphpxdebug:
    driver: bridge