# symf01
version: '3'

services:
  dbmaria:
    build: ./mariadb/
    container_name: cmari01
    hostname: hmari01
    
    environment:
      MYSQL_ROOT_PASSWORD:

    volumes:
      - ./db_volume/initdb:/docker-entrypoint-initdb.d/
      - ./db_volume/mysql:/var/lib/mysql
    ports:
      - "3306:3306"      
    networks:
      - netsymf01    
    command:
      'mysqld --innodb-flush-method=fsync'

  php:
    build: ./php7_fpm/
    container_name: ccgi01
    hostname: hcgi01
    volumes:
      - ./app:/code
    networks:
      - netsymf01
    depends_on:
      - dbmaria

  web:
    build: ./nginx/
    container_name: cngx1
    hostname: hngx1
    ports:
      - "8000:80"
    volumes:
      - ./app:/code
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - netsymf01
    depends_on:
      - dbmaria

networks:
  netsymf01:
    driver: bridge