# symf01
version: "3"

services:
  dbmaria:
    build: ./mariadb/
    container_name: cmari01
    hostname: hmari01

    # environment:
      # MYSQL_ROOT_PASSWORD: 1234

    volumes:
      - ./db_volume/initdb:/docker-entrypoint-initdb.d/
      - ./db_volume/mysql:/var/lib/mysql
    ports:
      - "3306:3306"      
    networks:
      - net01    
    command:
      'mysqld --innodb-flush-method=fsync'

  phpcgi:
    build: ./php7_fpm/
    container_name: ccgi01
    hostname: hcgi01
    volumes:
      - ./www/html:/var/www/html
    networks:
      - net01
    depends_on:
      - dbmaria

networks:
  net01:
    driver: bridge