FROM kalilinux/kali-rolling

RUN apt-get update && \
    apt -y install kali-linux-large

# RUN mkdir -p /root/bash
# RUN chmod -R +x /root/bash
# WORKDIR /root/bash

# COPY ./.bashrc-kl /root/.bashrc-kl
# COPY ./.vimrc /root/.vimrc
