# sebp/elk
FROM sebp/elk

RUN apt-get update
# RUN apt-get install -y iputils-ping 
# RUN apt-get install -y vim

# docker run -d -h helk --name celk -p 5044:5044 -p 5601:5601 -p 9200:9200 -p 9300:9300 elk