version: "3.8"

services:
  php:
    build: ./php8_fpm/
    container_name: cont-php
    hostname: php
    volumes:
      - ./app:/code
    expose:
      - "9000"
    networks:
      - netxap2

  apache:
    build:
      context: ./apache
    hostname: apache
    container_name: cont-apache
    ports:
      - "8080:80"
    networks:
      - netxap2

networks:
  netxap2:
    driver: bridge