version: "3.7"

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letxencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12
    restart: unless-stopped
    volumes:
      - certs:/etc/nginx/certs:rw
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx-nerdearla:
    image: pablokbs/hola-docker:nerdearla
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=nerdearla.example.com
      - LETSENCRYPT_HOST=example.com
      - LETSENCRYPT_EMAIL=eacevedof@yahoo.es

