version: '3'

services:
  web:
    image: nginx:latest
    container_name: cngx
    ports:
      - "3000:80"
    volumes:
      - ./app:/code
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - netngx

  php:
    image: php:7-fpm
    container_name: cfpm
    volumes:
      - ./app:/code
    networks:
      - netngx      

networks:
  netngx:
    driver: bridge