version: "3.5"

services:
  kalilinux:
    build:
      context: docker
    network_mode: "host" 
    hostname: hostkalilinux
    container_name: cont-kalilinux
    environment:
      TZ: UTC
    volumes:
      - ./docker/bash:/root/bash
      
    command: tail -f /dev/null
