# symf02
version: "3"

services:
  dbmaria:
    build: ./mariadb/
    container_name: cmari02
    hostname: hmari02

    environment:
      MYSQL_ROOT_PASSWORD: 1234

    volumes:
      - ./db_volume/initdb:/docker-entrypoint-initdb.d/
      - ./db_volume/mysql:/var/lib/mysql
    
    ports:
      - "3306:3306"      
    networks:
      - net
    command:
      'mysqld --innodb-flush-method=fsync'

  php:
    build: ./php7_fpm/
    container_name: cphp02
    hostname: hphp02
    volumes:
      - ./www/html:/var/www/html
    networks:
      - net
    entrypoint: 
      - /var/www/html/entrypoint.sh
    
  nginx:
    build: ./nginx/
    container_name: cngx02
    hostname: hngx02
    ports:
      - "2000:80"
    volumes:
      - ./www/html:/var/www/html
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net
    # depends_on:
    #   - php

networks:
  net:
    driver: bridge
