# sgi-phpmysql
version: "3.8"

services:
  apache:
    build:
      context: ./apache
    hostname: hostapache
    container_name: cont-apache
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html

networks:
  default:
    # this network is related to a main container with mariadb and all my databases
    # in this way I avoid creating a db container for each project check this file for more info:
    # prj_docker_imgs/mariadb-univ/docker-compose.yml
    name: mariadb-univ_net
    external: true