version: "3.5"

services:
  redis:
    # image: redis
    build:
      context: docker/redis
    hostname: redisdemo
    container_name: cont-redisdemo
    environment:
      TZ: ${TIME_ZONE}
      #REDIS_URL: ${REDIS_URL}

    volumes:
      - ./docker/redis/bash:/root/bash

    ports:
      - ${REDIS_PORT}:6379

    networks:
      - redis-net
      - mariadb-univ_net

networks:
  redis-net:
  mariadb-univ_net:
    external: true
