version: "3.5"

services:
  redis:
    image: redis
    hostname: redis
    container_name: cont-redis
    environment:
      TZ: ${TIME_ZONE}
      REDIS_SERVER: ${REDIS_SERVER}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - 6379:6379

    networks:
      - redis-net
      - mariadb-univ_net

networks:
  redis-net:
  mariadb-univ_net:
    external: true
