version: "3"

services:
  dbmaria:
    build: ./mariadb/
    container_name: cont-db
    hostname: host-db
    
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_api
      # MYSQL_USER: u1
      # MYSQL_PASSWORD: u1
    ports:
      - "3306:3306"      
    networks:
      - net-lumen
    command:
      'mysqld --innodb-flush-method=fsync'

  php:
    build: ./php-fpm/
    container_name: cont-php
    hostname: host-php
    volumes:
      - ./app/lumen:/appdata/www/lumen
    networks:
      - net-lumen
    depends_on:
      - dbmaria

  web:
    build: ./nginx/
    container_name: cont-web
    hostname: cont-web
    ports:
      # api
      - "8080:80"
      # front
      - "8090:90"
    volumes:
      - ./app/front:/appdata/www/front/dist
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net-lumen
    depends_on:
      - dbmaria

networks:
  net-lumen:
    driver: bridge